### ISSUE TITLE
Twitter Bearer Token - 403 Fails

### ISSUE THREAD

**Issue by Btibert3** [biolab/orange3-text#1037]
**Describe the bug**
The error response thrown inside Orange from Twitter suggests that the use of Bearer token is no longer the viable way of connecting to the API.

**To Reproduce**
1. Ensure the Text Add-On is installed and updated
2. Add the Twitter widget to the canvas
3. Double-click the widget, and add a valid bearer token for your application/project from the Twitter developer dashboard
4. Enter a search phrase

**Expected behavior**
The widget authenticates and searches for tweets per the settings.

**Actual behavior**
The following error message:

```
Api error: 403 Forbidden When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal.. Check if your API plan includes Tweets retrieval. The free plan doesn't allow Tweets retrieval anymore.
```

**Orange version:**
3.36.2

**Text add-on version:**
1.15.0

**Screenshots**
<img width="1510" alt="image" src="https://github.com/biolab/orange3-text/assets/203343/6647da50-e479-4d85-860f-1d289dd0e40d">

**Operating system:**
MacOS 14.3.1

**Additional context**
The documentation doesn't show adding a bearer token, but a key and a secret, which aligns to the error thrown.  https://orange3-text.readthedocs.io/en/latest/widgets/twitter-widget.html (Step 1 image is different from what is actually in the library).

**Comment by PrimozGodec** [comment]
What type of account do you have? If you have a free account version, it is not possible to download any tweets. https://github.com/biolab/orange3-text/issues/995

**Comment by Btibert3** [comment]
It is a free account, but would that impact the fact that the error thrown suggests a bearer token should not be used?   If bearer is accepted for non-free accounts than please feel free to close this issue.

**Comment by PrimozGodec** [comment]
I know the message could be better, but it is what Tweeter API throws, so we do not have any control here. This is also why we added the last sentence of the message that the plan may be wrong. According to the conversation here, https://github.com/twitterdev/Twitter-API-v2-sample-code/issues/58 bearer is accepted with any account, but with the Free plan, you cannot download tweets. 

This widget was developed before the API changed, and getting tweets without a paid account was possible. Now, it is pretty useless since it is costly to get any plan.
