### ISSUE TITLE
WordCloud Keep Weights Order for Topics

### ISSUE THREAD

**Issue by nikicc** [biolab/orange3-text#225]
##### Text version

0.2.4.dev

##### Expected behavior
One can observe words in the sorted by their importance according to a specific topic; i.e. sorted by their magnitude regardless of the sign.

##### Actual behavior
WC sorts words by weights hence the most interesting words are at the very top and at the very bottom.

##### Additional info (worksheets, data, screenshots, ...)
What happens with the size? Is it considered correctly for negative weights?

The schema to reproduce:
![screen shot 2017-03-31 at 17 21 52](https://cloud.githubusercontent.com/assets/713026/24557020/8c7368ee-1636-11e7-9d43-279a52bb274a.png)

**Comment by ajdapretnar** [comment]
I checked it and negative weights are not displayed. They appear in the list on the left, (incorrectly ?) ordered by absolute weight, but negatively weighted words don't appear in the visualization. Too bad, I agree we should fix this.

**Comment by kernc** [comment]
We agreed weakly related (negative) words should not be sorted on top.  The reason you don't see the negative words visualized is (probably) the hard limit on the number of words shown.

**Comment by ajdapretnar** [comment]
Ok, then the issue is that the ranking is absolute - negative words are mixed with positive. If I don't see a word in a word cloud, it's slightly confusing not seeing a word in the visualization.

I vote for better ranking!

<img width="1033" alt="screen shot 2017-05-26 at 14 33 35" src="https://cloud.githubusercontent.com/assets/12524972/26494711/522458ea-4220-11e7-9979-d1c258a94e0c.png">
