### ISSUE TITLE
Visualizing topics

### ISSUE THREAD

**Issue by GottM** [biolab/orange3-text#450]
I have seen a very cool way to display topics found by LDA analysis on a 2D diagram. BigML is offering that. Topics are shown as bubbles the sizes of which correspond to the frequencies of each topic and the positions of which on the diagram correspond to the proximity of the topics (how much they are likely to be relevant for the same record/text). I don't know whether we can achieve that with the existing tools in Orange. I have not found a way yet...

**Comment by ajdapretnar** [comment]
Solved by introducing a new output for Topic Modeling. Details in [documentation](https://orange.biolab.si/widget-catalog/text-mining/topicmodelling-widget/). It's a tiny bit convoluted, but we prefer utilizing existing Orange widgets rather than writing a new one that duplicates half of the functionalities.
