### ISSUE TITLE
Twitter: don't set Author as class variable

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#535]
Twitter widget automatically sets Author as class variable. Don't do it. Most of the time it doesn't make sense. One can always use Select Columns to do it explicitly.

**Comment by irgolic** [comment]
Knowing to use Select Columns is a UX issue. I mentioned this in https://github.com/biolab/orange3/issues/3997 in regard to CSV File Import, but a solution for all data set loading widgets should be devised.

Maybe if all data set widgets inherited the same base class, which contains File's attribute role controls? I guess this is more of an orange3 discussion, I'm just mentioning it here because it's relevant.
