### ISSUE TITLE
Word Cloud bug after topic modelling

### ISSUE THREAD

**Issue by rhythmsniper** [biolab/orange3-text#586]
##### Text version

1.1.0

##### Orange version

3.26

##### Expected behavior
A word cloud widget after a topic modelling widget should produce a word cloud of words in in the topic model and is reflective of preprocessed text which was inputed into the topic model widget. 

##### Actual behavior
The word cloud produced includes all characters and words regardless of previous pre-processing.

##### Steps to reproduce the behavior

See workflow for example. I loaded a CSV file consisting of the text of tweets (one document per row). I attached text pre-processing and added several customizations, including my own stopwords file and regexps. I then attached topic modelling, ran a 15 topic LDA. I then attached the word cloud widget to the topic modelling widget. The word cloud showed all text as if not processed at all. 

##### Additional info (worksheets, data, screenshots, ...)

![image](https://user-images.githubusercontent.com/70035422/95795858-66510180-0cb9-11eb-98cc-0583529fdafd.png)

**Comment by djukicn** [comment]
In order to get the expected behavior you have to double click on the connection between Topic Modelling and Word Cloud (1) and connect Selected Topic on the left with the Topic on the right. The Word Cloud should work only on the topic of your choice now. I think this should solve both problems you are reporting. Does it?
