### ISSUE TITLE
Tweet Profiler - Unknown error: JSONDecodeError

### ISSUE THREAD

**Issue by CarolinaNieto-thomascook** [biolab/orange3-text#598]
**Describe the bug**
Unknown error in Tweet Profiler 

**To Reproduce**
1. File CSV File import
2. select columns
3. Corpus
4. Preprocess Text 
5. Sentiment Analysis 
6. Tweet Profiler
7. Unknown error

**Expected behavior**
Description of emotions 

**Orange version:**
Orange - version 3.27.1

![Captura de Pantalla 2020-11-15 a la(s) 16 10 21](https://user-images.githubusercontent.com/74512609/99197644-0fe15200-2794-11eb-9b1c-fb7a0dc481d3.png)
![Captura de Pantalla 2020-11-15 a la(s) 22 43 48](https://user-images.githubusercontent.com/74512609/99197648-1374d900-2794-11eb-991a-7ab0927b487e.png)
![Captura de Pantalla 2020-11-15 a la(s) 16 10 21](https://user-images.githubusercontent.com/74512609/99197670-2b4c5d00-2794-11eb-88ed-cbf3bd04b0ee.png)

**Comment by djukicn** [comment]
Could you provide the data you used (if it's not private) and the workflow?

**Comment by CarolinaNieto-thomascook** [comment]
> Could you provide the data you used (if it's not private) and the workflow?

[ZIP.zip](https://github.com/biolab/orange3-text/files/5561603/ZIP.zip)
 

Here I attached the information data and workflow

**Comment by djukicn** [comment]
The issue is that the server where the models for Tweet Profiler are running sometimes returns an error. These models are still running on old servers and are planned to be moved to the new server soon. The error actually happens only occasionally and without any apparent pattern. I noticed that it seems to happen only when running on larger datasets. Until the models are migrated to new servers, you could try splitting the dataset into smaller chunks and joining the results but it's not guaranteed to work.
