### ISSUE TITLE
N-gram deduplication

### ISSUE THREAD

**Issue by HjalmarrSv** [biolab/orange3-text#914]
**Is your feature request related to a problem? Please describe.**
N-grams (Preprocess text) produce duplicates, e.g.
10 I
10 have
10 Github
10 I have
10 have Github
10 I have Github
...
1  I have Github now
They look bad in Word cloud.

**Describe the solution you'd like**
Maybe a check box next to n-gram setting. It would keep only the longest n-gram, when shorter n-grams completely fits in longer, and only when they have same frequency, e.g.
10 I have Github
...
1  I have Github now

Next level would be to look at different lengths of n-grams, and deduct from frequency on those n-grams, where only some belong to longer n-gram, e.g.
9 I have Github
...
1  I have Github now
Next level maybe another check box.

**Describe alternatives you've considered**
I have been thinking about filtering after Preprocess text, but have not passed phase of thinking. I have looked at Colocations widget, also very nice, but it forces you to choose bigram or trigram.

**Additional context**
This is actually a simple attempt to catch important phrases or multi-word nouns. In medical articles (pubmed) they are of varying lengths, why it is difficult to find them by just working with size of n-grams.

**Comment by PrimozGodec** [comment]
Hi. Thank you for submitting the issue, and apologies for the late reply. Isn't what you proposed simply setting both n-gram ranges to the same value? For example, if you want to have an n-gram range from 2 to 3 and you have the following text:

`It is a beautiful day.`

It will produce the following n-grams.

`["It is", "is a", "a beautiful", "beautiful day", "It is a", "is a beautiful", "a beautiful day"]`

Now if you remove everything included in longer n-grams, you get:

`["It is a", "is a beautiful", "a beautiful day"]`

This means you remove all the bi-grams and have only trigrams left. So isn't what you propose just using the range 3 to 3 in this example? So always, all 1-grams and 2-grams are part of 3-grams, so they get removed. Or in the case of a more extensive range, all the 1-grams, 2-grams, and 3-grams are also in 4-grams so that they would be removed.

I hope I got all the cases and understood what you meant exactly. Please let me know if it helps you. I will close this issue for now but feel free to reopen it if I am wrong.
