### ISSUE TITLE
Consider replacing pdfminer3k dependency with pdfminer.six

### ISSUE THREAD

**Issue by DManowitz** [biolab/orange3-text#964]
pdfminer3k has not had a release in almost 3 years, and according to their [repo](https://github.com/jaepil/pdfminer3k), the code hasn't been updated in about 7 years.  [pdfminer.six](https://github.com/pdfminer/pdfminer.six) is a much more recently maintained version.

**Comment by PrimozGodec** [comment]
Thanks for the suggestion. We know the package is not maintained; it was also removed from PyPi at some point and reloaded by the community. 

We are busy with other projects and would happily accept contributions. If you feel capable, we are happy to accept the pull request. Otherwise, it will probably need to wait for some time.

**Comment by PrimozGodec** [comment]
I proposed PR #994, which replaces pdfminer3k with pypdf. I didn't consider pdfminer.six since pypdf looks better maintained.
